# Generated by Django 4.0.5 on 2022-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Формы обратной связи'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default='default tittle', max_length=80, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
