# Generated by Django 4.0.5 on 2022-09-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentator_name',
            field=models.CharField(default='Аноним', max_length=100, verbose_name='Имя'),
        ),
    ]
